### ISSUE TITLE
Error when following README

### ISSUE THREAD

**Issue by simonharrer** [rzabini/gradle-jython#1]
With 

````
buildscript{
    repositories{
        mavenLocal()
        mavenCentral()
    }
    dependencies{
        classpath 'com.github.rzabini:gradle-jython:0+'
    }
}

apply plugin:'com.github.rzabini.gradle-jython'

task testJython(type:jython.JythonTask) {
    script file("scripts/syncLang.py")
}
```

I get

```
$ ./gradlew -b localization.gradle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'jabref'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find any matches for com.github.rzabini:gradle-jython:0+ as no versions of com.github.rzabini:gradle-jython are available.
     Searched in the following locations:
         file:/C:/Users/sh/.m2/repository/com/github/rzabini/gradle-jython/maven-metadata.xml
         file:/C:/Users/sh/.m2/repository/com/github/rzabini/gradle-jython/
         https://repo1.maven.org/maven2/com/github/rzabini/gradle-jython/maven-metadata.xml
         https://repo1.maven.org/maven2/com/github/rzabini/gradle-jython/
     Required by:
         :jabref:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.395 secs
```

**Comment by rzabini** [comment]
It seems that the library is not installed in your local maven repository.
Did you execute `gradlew publishToMavenLocal`? Because after that you should find the jar and the metadata under your .m2 directory.

**Comment by simonharrer** [comment]
Hm, I did not do this. 

But this way seems cumbersome to do this. I have implemented a custom solution for now, see https://github.com/JabRef/jabref/commit/0b8f7058981fae8faee8fc297d3a62fee660d766

It would be perfect if your plugin could be published to plugins.gradle.org and I would just use it from there.

**Comment by rzabini** [comment]
I agree, I did not published the plugin because I think it needs some more testing to assess its quality before releasing it, I will think about it.
If you need just the jython interpreter to execute a script without python dependencies, your solution is fine: I think that in this case a plugin may be of little utility. 
My aim in writing the plugin was in using some python-only tools in a gradle build: in particular I needed to produce odt files with [*docutils*] (http://docutils.sourceforge.net/docs/user/tools.html), and a [ *Sphinx*](http://sphinx-doc.org/) html site, starting from a set of *restructuredtext* (\*.rst) source files. To use such tools, some supporting libraries must be downloaded fromn the [*Pypi* site] (https://pypi.python.org), and used in the build.

**Comment by simonharrer** [comment]
Hm, yeah, but I think your plugin would be useful nonetheless. But thanks for the comments.

**Comment by rzabini** [comment]
Hi,
I published the plugins on the Gradle portal, you are welcome to try it and see if it fits your case.
